---
title: IJSE STU
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:year/:month/:day/:title"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
pygments: true
tagline: 
author:
  name: ijse
  email: i@ijser.cn
  github: ijse
  twitter: ijse
  feedburner: ijse
production_url: http://ijse.github.com
JB:
  version: 0.3.0
  BASE_PATH: false
  ASSET_PATH: false
  archive_path: "/archive.html"
  categories_path: "/categories.html"
  tags_path: "/tags.html"
  atom_path: "/atom.xml"
  rss_path: "/rss.xml"
  comments:
    provider: disqus
    disqus:
      short_name: ijserblog
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 123
      num_posts: 5
      width: 580
      colorscheme: light
  analytics:
    provider: google
    google:
      tracking_id: UA-39566119-1
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
  sharing:
    provider: false
prose:
  media: assets/images
  rooturl: _posts
  siteurl: http://www.ijser.cn/
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: published
      field:
        element: checkbox
        label: 是否发布
        value: false
    - name: title
      field:
        element: text
        label: Title
        value: ''
    - name: title
      field:
        element: text
        label: 标题
        value: ''
    - name: author
      field:
        element: text
        label: 作者
        value: ijse
        type: text
    - name: category
      field:
        element: text
        label: 类别
        value: article
    - name: date
      field:
        label: 日期
        element: text
        value: ''
    - name: comments
      field:
        element: checkbox
        label: 开启评论
        value: true
    - name: tags
      field:
        element: multiselect
        label: 标签
        placeholder: Choose Tags
        alterable: true
