---
new_page_extension: md
auto_deploy: true
admin_path: ".vuepress/public/admin/"
webhook_url: 
sections:
- type: document
  path: _posts/settings.md
  label: 网站设置
  read_only: false
- type: directory
  path: _posts
  label: 文章
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_env:
  - APP_ENV=forestry
  publish_env:
  - APP_ENV=production
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
