---
new_page_extension: md
auto_deploy: true
admin_path: ".vuepress/public/admin/"
webhook_url: 
sections:
- type: heading
  label: heading
- type: document
  path: ".vuepress/config.js"
  label: sadmin
- type: directory
  path: _posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_env:
  - NODE_ENV=forestry
  publish_env:
  - NODE_ENV=production
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
